### ISSUE TITLE
नव्यन्यायभाषाप्रदीप - महेशचन्द्र न्यायरत्न

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit/raw_etexts#27]
https://raw.githubusercontent.com/sanskrit/raw_etexts/master/nyAya-shAstram/navyanyayabhashapradipa.md

Book is already proof-read. 
I found this book very good to enter into navya nyaya language.

**Comment by vvasuki** [comment]
Thanks for contributing! Good idea to have a README.md file where one can record one's recommendations such as the above?
