### ISSUE TITLE
Two missing pages in Haravijaya edition scan

### ISSUE THREAD

**Issue by ppasedach** [sanskrit/raw_etexts#45]
The scan of the Haravijaya edition used here for OCR is lacking (at least) two pages. I have located a [scan of a reproduction of the same edition](https://archive.org/details/PyrG_haravijaya-of-rajanaka-ratnakara-with-pt.-durgaprasada-kavyamala-reprint-22-chau), and have extracted from it [the two missing pages](https://github.com/sanskrit/raw_etexts/files/6968562/HV-KM-missing-pages.pdf), which would need to be inserted before page 694 of the pdf, line 22477 of the e-text. I could just type it in, but maybe you like to OCR  and include it?

**Comment by vvasuki** [comment]
Did a quick scan with https://ocr.sanskritdictionary.com/# and inserted.
