### ISSUE TITLE
OCR Request: prākṛta-śabda-mahārṇava and prākṛta-lakṣmī-nāma-mālā

### ISSUE THREAD

**Issue by suhasm** [sanskrit/raw_etexts#50]
Welcome! Answer all these questions.

Do you want a text OCR-ed? If yes continue below. If not, clear all this text and type your issue.
- Has the text already been OCR-ed? Have you searched online (using both devanAgarI and latin transliterations)? For example in the large repositories of digitized texts listed [here](https://sites.google.com/site/samskrtamsfo/home/prakashanani/pathyam#TOC---Digitized-texts).
  - **Answer**:  The texts have not been OCRed.
- If you commit to proof-read the result within a reasonable timeframe (say 1 month for 300 pages), we will be specially excited to oblige you. Are you willing to make such a commitment? See [here](https://sites.google.com/site/sanskritcode/ocr/3-corrections) to get an idea of what it involves.
  - **Answer**: No. The texts are large and I do not have enough knowledge of Prakrit to proofread.
- Are you OK with the scan quality that we [currently offer](https://sites.google.com/site/sanskritcode/ocr/0-introduction#TOC-What-scan-quality-can-you-currently-offer-)? Or are you able to provide your own OCR text?
  - **Answer**: Yes, happy.
- What other factors should our OCR/ other volunteers consider when deciding whether to take up this request? In other words, what's so important about this text?
  - **Answer**:
    There are no online Prakrit dictionaries available. It poses a serious difficulty to those trying to read Prakrit literature. Making a Prakrit dictionary available will probably encourage more people to learn Prakrit and give up dependence on the chāyā. It will also help Jains, Buddhists, linguists and historians.
- Provide a link to the pdf of the _printed_ book which needs to be OCR-ed. You can host the pdf online on several sites such as  http://archive.org (← strongly recommended), http://dropbox.com or http://sites.google.com.
  - **Answer**: 
    prākṛta-śabda-mahārṇava: http://www.dli.ernet.in/handle/2015/348701 (This is the best quality pdf available AFAIK)
    prākṛta-lakṣmī-nāmamālā: https://archive.org/details/PaiaLacchiNammala001708HR
- Now for some details: please enter the following metadata (use both devanAgarI and latin alphabet forms if you can).
  - **Title**: pāia-sadda-mahaṇṇāvo (पाइअ-सद्द-महण्णवो)
  - **Author**: Pandit Hargovind Das T. Sheth
  - **Commentator**: NA
  - **Title**: pāia-lacchī-nāma-mālā (पाइअ-लच्छी-नाम-माला)
  - **Author**: Dhanapāla (धनपालः)
  - **Commentator**: NA
- Is there any other information you want to provide?
  - **Answer**: We should upload OCRed pdfs of the texts to archive, even if not proofread. It will help many. 

Ok - thanks for answering the above questions 🙏. Subscribe to this thread to stay updated.

**Comment by Andhrabharati** [comment]
@vvasuki 
The full text of pāia-sadda-mahaṇṇāvo (पाइअ-सद्द-महण्णवो) is available now at DSAL, and is with a reasonably good quality.

**Comment by vvasuki** [comment]
Yes - got it. Closing this obsolete issue.
