### ISSUE TITLE
शबरभाष्यस्य पूर्णः पाठः

### ISSUE THREAD

**Issue by vvasuki** [sanskrit/raw_etexts#6]
https://github.com/sanskrit/raw_etexts/commit/6e8d738812769e99d6bb20c278932fc211cd4ceb इत्यनेन शबरभाष्यम् अङ्कीकृतं समर्पितम्। ममाध्ययनाय बहूपादेयम्। किन्तु तत्र कानिचन पृष्ठानि न विद्यन्ते - प्रथमाध्याये यथा +उप९९ एव पृष्ठानि। पुनः पृष्ठसङ्ख्याक्रमे व्यत्यासो ऽपेक्षितः - ```
1990020102811 - Mimamsa Darshana, Jaimini Muni, 1130p, (मीमांसादर्शनम् १ - १२ अध्यायाः CSS)_12_1.jpg.txt``` इत्यस्य स्थाने 
```1990020102811 - Mimamsa Darshana, Jaimini Muni, 1130p, (मीमांसादर्शनम् १ - १२ अध्यायाः CSS)_12_001.jpg.txt``` इति स्यात्। 

अतः परिष्कारो विधेयः। प्रत्यध्यायम् एका सञ्चिकेति सङ्गृह्य प्रेषयितुं शक्यं वा @lalitaalaalitah ?

**Comment by lalitaalaalitah** [comment]
1.
PDF was downloaded from the DLI server, the original file doesn't have the mentioned page.
OCR-ed txt files correspond to pdf. So, unless I get a scan of the page, or a complete scan of the same edition; we are out of luck.
2.
Numbering is human readable form, the 0001 trend is for machines. My initial PDF breaking script was using human readable numbers, so it will stay same.
You may use a small script to rename them.
3.
Separating chapters needs time. I'm not able to dedicate any. The person studying must be able to do the same.

**Comment by vvasuki** [comment]
1. It seems odd that there are no more than exactly 99 pages in any given adhyAya.
2. ok.
3. Separating chapters, as in adhyAya, does not need time - it's already separated, see the appropriate portion filename - "10_11"  (wasn't talking about that anyway).

Will likely delete and replace - No sweat.

**Comment by lalitaalaalitah** [comment]
I can understand from your reply that your expectation, amusement, etc. are all originating from an assumption that all chapters have 99 pages. I bet that you didn't get any chance to check the PDF from archive, etc.
Let me clarify, that the number pattern just means that the script which I used to convert PDF to individual pages was handling only 100 pages at a time, and it named them from 0 to 99. It has no relation to chapters of the book.
So, it must be clear to you now, that dividing is time consuming work.
Numbering pattern can be changed to continuous. But, I'm not willing to invest time in that.
My OCR are similar to this. I may correct the script to number PDF images continuously. But, that doesn't affect what is already OCR-ed.
I suggest you to have a small script to automate this and replace/edit, as you suggested.

**Comment by vvasuki** [comment]
Your info is wrong, sir. Let me reiterate:

## Chapters are already separated, and this can be made out from the file name:
First line of `...2_0.jpg.txt`:
```
२ द्विनीयाध्याये १ प्रथमः पाद: |
```

First line of `...5_0.jpg.txt`:
```
५ पश्चमाध्याये १ प्रथमः पादः ।
```
and so on.

## Chapters thus separated are incomplete.
Chapter 4 has 100 files, the last of which ends with:
```श्वोभूते हविरभिवासनम् । अभिवासनं कृत्वा अमावास्यायां वेदिः```

Chapter 3 has 100 files, the last of which ends with:
```णि वेदे श्रूयते । तस्मात् स्वाध्यायोऽध्येतव्य इति । सत्यतस्मिन् व.```
and so on.

## Conclusion
Without even looking at the pdf, my assumption is that your script somehow missed ocring certain pages in each chapter.

**Comment by vvasuki** [comment]
Actually, I discovered that I was wrong about the chapter-based numbering upon opening more files:

```10_0.jpg.txt``` begins with : ```१० दशमाध्याये ५ पश्चमः पादः ।```.
```12_0.jpg.txt``` begins with : ```१२ द्वादशाध्याये २ द्वितीयः पादः ```

So the output is stranger than I thought.

**Comment by lalitaalaalitah** [comment]
I'll help you understand again:
The script I used to break was taking 100 pages of a PDF at one time, so if the book had 1200 pages(just by luck in this case), it will do the same for 12 times and add this number to name.
it then looped over those 100 pages to generate 100 images bearing numbers from 0 to 99. So, you get _0_1, ....... _12_01, etc.

**Comment by vvasuki** [comment]
Thanks for the patient explanation! I realize now that I was mistaking the page headers for chapter titles. I have fixed the file names, and combined into a single file. I might split into separate chapters later.
